### ISSUE TITLE
Need help with the image upload

### ISSUE THREAD

**Issue by kalsmic** [kalsmic/iReporterApi#54]
Kindly help me figure out what I am not doing right. I have failed to implement the image upload on Heroku yet it works locally on my pc and also in postman.

I get this error when I try to upload the file using the UI
![error](https://user-images.githubusercontent.com/24764476/52614501-e7cc0d00-2ea2-11e9-9b7a-593739a3a4ef.png)

**Image upload form**
https://github.com/kalsmic/iReporterApi/blob/a4b93ee8aeadfe396ab3c71a1dcbd71b7e24404e/UI/incidents/details.html#L122-L127
**Javascript Code for the image upload** 
https://github.com/kalsmic/iReporterApi/blob/a4b93ee8aeadfe396ab3c71a1dcbd71b7e24404e/UI/static/js/image_upload.js#L2-L27
**Python backend code for the image upload endpoint**
https://github.com/kalsmic/iReporterApi/blob/a4b93ee8aeadfe396ab3c71a1dcbd71b7e24404e/api/views/create_incident.py#L81-L130

@NicholusMuwonge @Rhytah @JamesMudidi @sanya-kenneth @frankopkusianwar @AtamaZack @ManuelDominic @KabohaJeanMark @nadralia @reifred @llwasampijja @richien @Genza999 @3Nakajugo @e-ian @Manorlds-Eaglespark @PatrickMugayaJoel @bisonlou @v1b3m @mwinel @sebbss, @kbjude

**Comment by Genza999** [comment]
Also having the same issue. Still haven't figured out how to go about it. Someone please help!

**Comment by reifred** [comment]
Am also facing the same challenge

**Comment by llwasampijja** [comment]
@kalsmic have you updated the image_upload.js file, bcos it states there is an error on line 28, but there is no line 28 in the code?

**Comment by kalsmic** [comment]
> @kalsmic have you updated the image_upload.js file, bcos it states there is an error on line 28, but there is no line 28 in the code?

No, I have not

**Comment by kalsmic** [comment]
Thanks, colleagues for helping out, I was able to figure out the issue. it is with the following line of code.
https://github.com/kalsmic/iReporterApi/blob/a4b93ee8aeadfe396ab3c71a1dcbd71b7e24404e/UI/static/js/image_upload.js#L19
The content type is image and not JSON. I have removed this line and cleared the bug.
